server:
  port: 8083
spring:
  datasource:
    username: cms
    password: fzu23
    url: jdbc:mysql://101.132.35.228:3306/courier_system?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mini-app-user:
  appid: wx3fcad718a821d77d
  secret: ba8459cc58de7acbcc67998c291a7d95
mini-app-courier:
  appid: wx0b1aa687cba0c146
  secret: 8b52a729b94d62b8fb1488339606e447

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_delete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    mapUnderscoreToCamelCase: false


