server:
  port: 8083
spring:
  datasource:
    username: cms
    password: fzu23
    url: jdbc:mysql://101.132.35.228:3306/courier_system?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mini-app-user:
  appid: wx3fcad718a821d77d
  secret: ba8459cc58de7acbcc67998c291a7d95
mini-app-courier:
  appid: wx0b1aa687cba0c146
  secret: 8b52a729b94d62b8fb1488339606e447

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_delete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    mapUnderscoreToCamelCase: false

# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期 这里设置为10分钟
  timeout: 1800
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

